# Generated by Django 5.1.7 on 2025-03-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("request", "Request"), ("donation", "Donation")],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("group", models.CharField(max_length=50, null=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("standard", "Standard"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_posted", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("date_posted", models.DateField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "idProof",
                    models.FileField(blank=True, null=True, upload_to="id_proofs/"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("User", "User"),
                            ("Manager", "Manager"),
                        ],
                        default="User",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="app1.feed",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feed",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.person"
            ),
        ),
    ]
